[Infra] Support publishing iOS SDK in development version

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -10,109 +10,109 @@ on:
         type: string
 
 jobs:
-  android-explorer-build:
-    timeout-minutes: 60
-    if: ${{ inputs.dry-run == false }}
-    runs-on: lynx-ubuntu-22.04-large
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Build Explorer App
-        uses: ./lynx/.github/actions/android-explorer-build
-        with:
-          build-type: release
-      - name: push to release
-        uses: ncipollo/release-action@v1
-        with:
-          tag: ${{ inputs.version }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          artifacts: '${{ github.workspace }}/lynx/explorer/android/lynx_explorer/build/outputs/apk/noasan/release/LynxExplorer-noasan-release.apk'
-          allowUpdates: true
+  # android-explorer-build:
+  #   timeout-minutes: 60
+  #   if: ${{ inputs.dry-run == false }}
+  #   runs-on: lynx-ubuntu-22.04-large
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Build Explorer App
+  #       uses: ./lynx/.github/actions/android-explorer-build
+  #       with:
+  #         build-type: release
+  #     - name: push to release
+  #       uses: ncipollo/release-action@v1
+  #       with:
+  #         tag: ${{ inputs.version }}
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         artifacts: '${{ github.workspace }}/lynx/explorer/android/lynx_explorer/build/outputs/apk/noasan/release/LynxExplorer-noasan-release.apk'
+  #         allowUpdates: true
 
-  ios-explorer-build:
-    timeout-minutes: 60
-    runs-on: lynx-darwin-14-medium
-    strategy:
-      matrix:
-        arch: [arm64, x86_64]
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-      - name: Setup Ruby Cache
-        uses: ./lynx/.github/actions/ios-common-deps
-      - name: Install iOS Dependencies
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 20
-          max_attempts: 3
-          command: |-
-            set -e
-            cd $GITHUB_WORKSPACE/lynx
-            source tools/envsetup.sh
-            pushd explorer/darwin/ios/lynx_explorer
-            git config --global url."https://github.com/".insteadOf "git@github.com:"
-            bash bundle_install.sh
-            popd
-      - name: Build Explorer App
-        run: |-
-          cd $GITHUB_WORKSPACE/lynx
-          source tools/envsetup.sh
-          pushd explorer/darwin/ios/lynx_explorer
-          xcodebuild -workspace LynxExplorer.xcworkspace -scheme LynxExplorer -configuration Debug -arch ${{ matrix.arch }} -archivePath build/LynxExplorer.xcarchive -derivedDataPath iOSCoreBuild/DerivedData -resultBundlePath results_bundle -showBuildTimingSummary -sdk iphonesimulator LD_GENERATE_MAP_FILE=YES LD_MAP_FILE_PATH=Build/linkmap.txt -jobs 24 build
-          popd
-          tar --strip-components 10 -czvf LynxExplorer-${{ matrix.arch }}.app.tar.gz explorer/darwin/ios/lynx_explorer/iOSCoreBuild/DerivedData/Build/Products/Debug-iphonesimulator/LynxExplorer.app
-      - name: push explorer to release
-        uses: ncipollo/release-action@v1
-        if: ${{ inputs.dry-run == false }}
-        with:
-          tag: ${{ inputs.version }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          artifacts: '${{ github.workspace }}/lynx/LynxExplorer-${{ matrix.arch }}.app.tar.gz'
-          allowUpdates: true
+  # ios-explorer-build:
+  #   timeout-minutes: 60
+  #   runs-on: lynx-darwin-14-medium
+  #   strategy:
+  #     matrix:
+  #       arch: [arm64, x86_64]
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #     - name: Setup Ruby Cache
+  #       uses: ./lynx/.github/actions/ios-common-deps
+  #     - name: Install iOS Dependencies
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         timeout_minutes: 20
+  #         max_attempts: 3
+  #         command: |-
+  #           set -e
+  #           cd $GITHUB_WORKSPACE/lynx
+  #           source tools/envsetup.sh
+  #           pushd explorer/darwin/ios/lynx_explorer
+  #           git config --global url."https://github.com/".insteadOf "git@github.com:"
+  #           bash bundle_install.sh
+  #           popd
+  #     - name: Build Explorer App
+  #       run: |-
+  #         cd $GITHUB_WORKSPACE/lynx
+  #         source tools/envsetup.sh
+  #         pushd explorer/darwin/ios/lynx_explorer
+  #         xcodebuild -workspace LynxExplorer.xcworkspace -scheme LynxExplorer -configuration Debug -arch ${{ matrix.arch }} -archivePath build/LynxExplorer.xcarchive -derivedDataPath iOSCoreBuild/DerivedData -resultBundlePath results_bundle -showBuildTimingSummary -sdk iphonesimulator LD_GENERATE_MAP_FILE=YES LD_MAP_FILE_PATH=Build/linkmap.txt -jobs 24 build
+  #         popd
+  #         tar --strip-components 10 -czvf LynxExplorer-${{ matrix.arch }}.app.tar.gz explorer/darwin/ios/lynx_explorer/iOSCoreBuild/DerivedData/Build/Products/Debug-iphonesimulator/LynxExplorer.app
+  #     - name: push explorer to release
+  #       uses: ncipollo/release-action@v1
+  #       if: ${{ inputs.dry-run == false }}
+  #       with:
+  #         tag: ${{ inputs.version }}
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         artifacts: '${{ github.workspace }}/lynx/LynxExplorer-${{ matrix.arch }}.app.tar.gz'
+  #         allowUpdates: true
 
-  android-sdk-release:
-    runs-on: lynx-ubuntu-22.04-large
-    if: ${{ inputs.dry-run == false }}
-    timeout-minutes: 60
-    steps:
-      - name: Download Source
-        uses: actions/checkout@v4.2.2
-        with:
-          path: lynx
-      - name: Install Common Dependencies
-        uses: ./lynx/.github/actions/common-deps
-        with:
-          cache-backend: 'lynx-infra'
-      - name: Android SDK Release
-        uses: ./lynx/.github/actions/android-sdk-release
-        with:
-          version: ${{ inputs.version }}
-          signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
-          signingPassword: ${{ secrets.SIGNING_PASSWORD }}
-          signingSecretKey: ${{ secrets.SIGNING_SECRET_KEY }}
-          abiList: 'armeabi-v7a,x86,x86_64,arm64-v8a'
-      - name: Package maven artifacts
-        run: |-
-          cd $GITHUB_WORKSPACE/lynx
-          pushd platform/android
-          ./gradlew zipArtifacts -Pversion=${{ inputs.version }} getArtifactList
-          popd
-          pushd platform/android/build
-          artifact_list=$(<artifact-list)
-          echo "::set-output name=artifact_list::$artifact_list"
-          popd
-        id: build_artifact
-      - name: Publish artifact to maven
-        uses: lynx-infra/maven-publish-action@c48e3067642c7ceccf807cd52e6644a257cd8ded
-        with:
-          portal_api_token: ${{ secrets.PORTAL_API_TOKEN }}
-          artifact_path_list: ${{ steps.build_artifact.outputs.artifact_list }}
+  # android-sdk-release:
+  #   runs-on: lynx-ubuntu-22.04-large
+  #   if: ${{ inputs.dry-run == false }}
+  #   timeout-minutes: 60
+  #   steps:
+  #     - name: Download Source
+  #       uses: actions/checkout@v4.2.2
+  #       with:
+  #         path: lynx
+  #     - name: Install Common Dependencies
+  #       uses: ./lynx/.github/actions/common-deps
+  #       with:
+  #         cache-backend: 'lynx-infra'
+  #     - name: Android SDK Release
+  #       uses: ./lynx/.github/actions/android-sdk-release
+  #       with:
+  #         version: ${{ inputs.version }}
+  #         signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
+  #         signingPassword: ${{ secrets.SIGNING_PASSWORD }}
+  #         signingSecretKey: ${{ secrets.SIGNING_SECRET_KEY }}
+  #         abiList: 'armeabi-v7a,x86,x86_64,arm64-v8a'
+  #     - name: Package maven artifacts
+  #       run: |-
+  #         cd $GITHUB_WORKSPACE/lynx
+  #         pushd platform/android
+  #         ./gradlew zipArtifacts -Pversion=${{ inputs.version }} getArtifactList
+  #         popd
+  #         pushd platform/android/build
+  #         artifact_list=$(<artifact-list)
+  #         echo "::set-output name=artifact_list::$artifact_list"
+  #         popd
+  #       id: build_artifact
+  #     - name: Publish artifact to maven
+  #       uses: lynx-infra/maven-publish-action@c48e3067642c7ceccf807cd52e6644a257cd8ded
+  #       with:
+  #         portal_api_token: ${{ secrets.PORTAL_API_TOKEN }}
+  #         artifact_path_list: ${{ steps.build_artifact.outputs.artifact_list }}
 
   ios-sdk-publish:
     timeout-minutes: 60
@@ -131,26 +131,20 @@ jobs:
           cache-backend: github
       - name: Setup Ruby Cache
         uses: ./lynx/.github/actions/ios-common-deps
-      - name: Prepare cocoapods publish source
-        run: |-
-          cd $GITHUB_WORKSPACE/lynx
-          source tools/envsetup.sh
-          python3 tools/ios_tools/cocoapods_publish_helper.py --prepare-source --tag ${{ inputs.version }} --component all
-      - name: Push iOS SDK to release
-        uses: ncipollo/release-action@v1
+      - name: Publish iOS SDK
+        uses: ./lynx/.github/actions/ios-sdk-publish
         with:
+          version: ${{ inputs.version }}
           tag: ${{ inputs.version }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          artifacts: '${{ github.workspace }}/lynx/*.zip'
-          replacesArtifacts: true
-          allowUpdates: true
-      - name: Publish to CocoaPods Repo
-        env:
-          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
-        run: |-
-          cd $GITHUB_WORKSPACE/lynx
-          source tools/envsetup.sh
-          git config --global user.name "lynx.authors"
-          git config --global user.email "lynx.authors@users.noreply.github.com"
-          python3 tools/ios_tools/skip_pod_lint.py --source public
-          python3 tools/ios_tools/cocoapods_publish_helper.py --publish --component all  --tag ${{ inputs.version }}
+          cocoapods_trunk_token: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          component: all
+      - name: Publish iOS dev SDK
+        uses: ./lynx/.github/actions/ios-sdk-publish
+        with:
+          version: ${{ inputs.version }}-dev
+          tag: ${{ inputs.version }}
+          cocoapods_trunk_token: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
+          prepare_command: "export LYNX_ENABLE_RECORDER=1"
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          component: all
